In [3]:
import requests,re

In [4]:
from bs4 import BeautifulSoup;

In [5]:
import numpy as np

In [1]:
import pandas as pd

#### Batting(Test)

In [ ]:
player=[]
matches=[]
inn=[]
no=[]
runs=[]
hs=[]
avg=[]
bf=[]
sr=[]
_100=[]
_50=[]
_0=[]
_4s=[]
_6s=[]
season=[]
format_=[]


for s in range(2013,2023):    
    url=f'https://stats.espncricinfo.com/ci/engine/stats/index.html?class=1;filter=advanced;orderby=runs;page=1;season={s};template=results;type=batting;view=season'
    response=requests.get(url,headers = {'User-Agent':'Mozilla/5.0'})
    page = BeautifulSoup(response.text)
    for i in page.find_all('tr',class_='data1'):
        if re.findall(r'[A-Za-z].+',i.text):
            player.append(''.join(re.findall(r'[A-Za-z].+',i.text)))
        else:
            player.append(np.nan)
        if re.findall(r'[A-Za-z].+\s(.+)',i.text):
            matches.append(''.join(re.findall(r'[A-Za-z].+\s(.+)',i.text)))
        else:
            matches.append(np.nan)
        if re.findall(r'[A-Za-z].+\s.+\s(\d+)',i.text):
            inn.append(''.join(re.findall(r'[A-Za-z].+\s.+\s(\d+)',i.text)))
        else:
            inn.append(np.nan)
        if re.findall(r'[A-Za-z].+\s.+\s\d+\s(\d+)',i.text):
            no.append(''.join(re.findall(r'[A-Za-z].+\s.+\s\d+\s(\d+)',i.text)))
        else:
            no.append(np.nan)
        if re.findall(r'[A-Za-z].+\s.+\s\d+\s\d+\s(\d.+)',i.text):
            runs.append(''.join(re.findall(r'[A-Za-z].+\s.+\s\d+\s\d+\s(\d.+)',i.text)))
        else:
            runs.append(np.nan)
        if re.findall(r'[A-Za-z].+\s.+\s\d+\s\d+\s\d+\s(\d.+)',i.text):
            hs.append(''.join(re.findall(r'[A-Za-z].+\s.+\s\d+\s\d+\s\d+\s(\d.+)',i.text)))
        else:
            hs.append(np.nan)
        if re.findall(r'[A-Za-z].+\s.+\s\d+\s\d+\s\d+\s\d.+\s(-|\d.+\..+)',i.text):
            avg.append(''.join(re.findall(r'[A-Za-z].+\s.+\s\d+\s\d+\s\d+\s\d.+\s(-|\d.+\..+)',i.text)))
        else:
            avg.append(np.nan)
        if re.findall(r'[A-Za-z].+\s.+\s\d+\s\d+\s\d+\s\d.+\s\d.+\..+\s(\d.+)',i.text):
            bf.append(''.join(re.findall(r'[A-Za-z].+\s.+\s\d+\s\d+\s\d+\s\d.+\s\d.+\..+\s(\d.+)',i.text)))
        else:
            bf.append(np.nan)
        if re.findall(r'[A-Za-z].+\s.+\s\d+\s\d+\s\d+\s\d.+\s\d.+\..+\s\d.+\s(\d.+)',i.text):
            sr.append(''.join(re.findall(r'[A-Za-z].+\s.+\s\d+\s\d+\s\d+\s\d.+\s\d.+\..+\s\d.+\s(\d.+)',i.text)))
        else:
            sr.append(np.nan)
        if re.findall(r'[A-Za-z].+\s.+\s\d+\s\d+\s\d+\s\d.+\s\d.+\..+\s\d.+\s\d.+\s(\d+)',i.text):
            _100.append(''.join(re.findall(r'[A-Za-z].+\s.+\s\d+\s\d+\s\d+\s\d.+\s\d.+\..+\s\d.+\s\d.+\s(\d+)',i.text)))
        else:
            _100.append(np.nan)
        if re.findall(r'[A-Za-z].+\s.+\s\d+\s\d+\s\d+\s\d.+\s\d.+\..+\s\d.+\s\d.+\s\d+\s(\d+)',i.text):
            _50.append(''.join(re.findall(r'[A-Za-z].+\s.+\s\d+\s\d+\s\d+\s\d.+\s\d.+\..+\s\d.+\s\d.+\s\d+\s(\d+)',i.text)))
        else:
            _50.append(np.nan)
        if re.findall(r'[A-Za-z].+\s.+\s\d+\s\d+\s\d+\s\d.+\s\d.+\..+\s\d.+\s\d.+\s\d+\s\d+\s(\d+)',i.text):
            _0.append(''.join(re.findall(r'[A-Za-z].+\s.+\s\d+\s\d+\s\d+\s\d.+\s\d.+\..+\s\d.+\s\d.+\s\d+\s\d+\s(\d+)',i.text)))
        else:
            _0.append(np.nan)
        if re.findall(r'[A-Za-z].+\s.+\s\d+\s\d+\s\d+\s\d.+\s\d.+\..+\s\d.+\s\d.+\s\d+\s\d+\s\d+\s(\d+)',i.text):
            _4s.append(''.join(re.findall(r'[A-Za-z].+\s.+\s\d+\s\d+\s\d+\s\d.+\s\d.+\..+\s\d.+\s\d.+\s\d+\s\d+\s\d+\s(\d+)',i.text)))
        else:
            _4s.append(np.nan)
        if re.findall(r'[A-Za-z].+\s.+\s\d+\s\d+\s\d+\s\d.+\s\d.+\..+\s\d.+\s\d.+\s\d+\s\d+\s\d+\s\d+\s(\d+)',i.text):
            _6s.append(''.join(re.findall(r'[A-Za-z].+\s.+\s\d+\s\d+\s\d+\s\d.+\s\d.+\..+\s\d.+\s\d.+\s\d+\s\d+\s\d+\s\d+\s(\d+)',i.text)))
        else:
            _6s.append(np.nan)
        if re.findall(r'[A-Za-z].+\s.+\s\d+\s\d+\s\d+\s\d.+\s\d.+\..+\s\d.+\s\d.+\s\d+\s\d+\s\d+\s\d+\s\d+\s(\d+)',i.text):
            season.append(''.join(re.findall(r'[A-Za-z].+\s.+\s\d+\s\d+\s\d+\s\d.+\s\d.+\..+\s\d.+\s\d.+\s\d+\s\d+\s\d+\s\d+\s\d+\s(\d+)',i.text)))
        else:
            season.append(np.nan)

In [21]:
df=pd.DataFrame({'player':player,
                 'matches':matches,
                 'inn':inn,
                 'no':no,
                 'runs':runs,
                 'hs':hs,
                 'avg':avg,
                 'bf':bf,
                 'sr':sr,
                 '_100':_100,
                 '_50':_50,
                 '_0':_0,
                 '_4s':_4s,
                 '_6s':_6s,
                 'season':season})

In [22]:
df

,player,matches,inn,no,runs,hs,avg,bf,sr,_100,_50,_0,_4s,_6s,season
0,IR Bell (ENG),7,14,1,635,113,48.84,1382,45.94,3,2,0,85,1,2013
1,JE Root (ENG),7,14,1,582,180,44.76,1256,46.33,2,2,0,67,2,2013
2,AN Cook (ENG),7,14,0,494,130,35.28,1178,41.93,1,3,1,59,0,2013
3,IJL Trott (ENG),7,14,0,492,76,35.14,1000,49.20,0,4,2,65,0,2013
4,SR Watson (AUS),5,10,0,418,176,41.80,650,64.30,1,1,0,57,2,2013
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
484,MG Bracewell (NZ),2,4,0,96,49,24.00,163,58.89,0,0,0,15,2,2022
485,Najmul Hossain Shanto (BAN),4,7,0,96,42,13.71,268,35.82,0,0,1,16,0,2022
486,KS Williamson (NZ),2,4,0,96,48,24.00,235,40.85,0,0,0,15,0,2022
487,AT Carey (AUS),2,3,1,89,45,44.50,136,65.44,0,0,0,10,0,2022
488,TG Southee (NZ),3,6,0,86,33,14.33,94,91.48,0,0,1,14,1,2022

In [ ]:
df.to_csv('batting.csv', index=False)

#### Bowling(Test)

In [ ]:
player=[]
matches=[]
inn=[]
overs=[]
maiden=[]
runs=[]
wkts=[]
bb_inn=[]
bb_match=[]
avg=[]
econ=[]
sr=[]
_4w=[]
_5w=[]
season=[]

for s in range(2013,2023):    
    url=f'https://stats.espncricinfo.com/ci/engine/stats/index.html?class=1;filter=advanced;orderby=runs;page={p};season={s};template=results;type=bowling;view=season'
    response=requests.get(url,headers = {'User-Agent':'Mozilla/5.0'})
    page = BeautifulSoup(response.text)
    for i in page.find_all('tr',class_='data1'):
        if re.findall(r'[A-Za-z].+',i.text):
            player.append(''.join(re.findall(r'[A-Za-z].+',i.text)))
        else:
            player.append(np.nan)
        if re.findall(r'[A-Za-z].+\n(\d*)',i.text):
            matches.append(''.join(re.findall(r'[A-Za-z].+\n(\d*)',i.text)))
        else:
            matches.append(np.nan)
        if re.findall(r'[A-Za-z].+\s.+\s(\d+)',i.text):
            inn.append(''.join(re.findall(r'[A-Za-z].+\s.+\s(\d+)',i.text)))
        else:
            inn.append(np.nan)
        if re.findall(r'[A-Za-z].+\s.+\s\d+\s(\d.+)',i.text):
            overs.append(''.join(re.findall(r'[A-Za-z].+\s.+\s\d+\s(\d.+)',i.text)))
        else:
            overs.append(np.nan)
        if re.findall(r'[A-Za-z].+\s.+\s\d+\s\d.+\s(\d+)',i.text):
            maiden.append(''.join(re.findall(r'[A-Za-z].+\s.+\s\d+\s\d.+\s(\d+)',i.text)))
        else:
            maiden.append(np.nan)
        if re.findall(r'[A-Za-z].+\s.+\s\d+\s\d.+\s\d+\s(\d+)',i.text):
            runs.append(''.join(re.findall(r'[A-Za-z].+\s.+\s\d+\s\d.+\s\d+\s(\d+)',i.text)))
        else:
            runs.append(np.nan)
        if re.findall(r'[A-Za-z].+\s.+\s\d+\s\d.+\s\d+\s\d+\s(\d+)',i.text):
            wkts.append(''.join(re.findall(r'[A-Za-z].+\s.+\s\d+\s\d.+\s\d+\s\d+\s(\d+)',i.text)))
        else:
            wkts.append(np.nan)
        if re.findall(r'[A-Za-z].+\s.+\s\d+\s\d.+\s\d+\s\d+\s\d+\s(\d.+)',i.text):
            bb_inn.append(''.join(re.findall(r'[A-Za-z].+\s.+\s\d+\s\d.+\s\d+\s\d+\s\d+\s(\d.+)',i.text)))
        else:
            bb_inn.append(np.nan)
        if re.findall(r'[A-Za-z].+\s.+\s\d+\s\d.+\s\d+\s\d+\s\d+\s\d.+\s(\d.+)',i.text):
            bb_match.append(''.join(re.findall(r'[A-Za-z].+\s.+\s\d+\s\d.+\s\d+\s\d+\s\d+\s\d.+\s(\d.+)',i.text)))
        else:
            bb_match.append(np.nan)
        if re.findall(r'[A-Za-z].+\s.+\s\d+\s\d.+\s\d+\s\d+\s\d+\s\d.+\s\d.+\s(\d.+)',i.text):
            avg.append(''.join(re.findall(r'[A-Za-z].+\s.+\s\d+\s\d.+\s\d+\s\d+\s\d+\s\d.+\s\d.+\s(\d.+)',i.text)))
        else:
            avg.append(np.nan)
        if re.findall(r'[A-Za-z].+\s.+\s\d+\s\d.+\s\d+\s\d+\s\d+\s\d.+\s\d.+\s\d.+\s(\d.+)',i.text):
            econ.append(''.join(re.findall(r'[A-Za-z].+\s.+\s\d+\s\d.+\s\d+\s\d+\s\d+\s\d.+\s\d.+\s\d.+\s(\d.+)',i.text)))
        else:
            econ.append(np.nan)
        if re.findall(r'[A-Za-z].+\s.+\s\d+\s\d.+\s\d+\s\d+\s\d+\s\d.+\s\d.+\s\d.+\s\d.+\s(\d.+)',i.text):
            sr.append(''.join(re.findall(r'[A-Za-z].+\s.+\s\d+\s\d.+\s\d+\s\d+\s\d+\s\d.+\s\d.+\s\d.+\s\d.+\s(\d.+)',i.text)))
        else:
            sr.append(np.nan)
        if re.findall(r'[A-Za-z].+\s.+\s\d+\s\d.+\s\d+\s\d+\s\d+\s\d.+\s\d.+\s\d.+\s\d.+\s\d.+\s(\d)',i.text):
            _4w.append(''.join(re.findall(r'[A-Za-z].+\s.+\s\d+\s\d.+\s\d+\s\d+\s\d+\s\d.+\s\d.+\s\d.+\s\d.+\s\d.+\s(\d)',i.text)))
        else:
            _4w.append(np.nan)
        if re.findall(r'[A-Za-z].+\s.+\s\d+\s\d.+\s\d+\s\d+\s\d+\s\d.+\s\d.+\s\d.+\s\d.+\s\d.+\s\d\s(\d)',i.text):
            _5w.append(''.join(re.findall(r'[A-Za-z].+\s.+\s\d+\s\d.+\s\d+\s\d+\s\d+\s\d.+\s\d.+\s\d.+\s\d.+\s\d.+\s\d\s(\d)',i.text)))
        else:
            _5w.append(np.nan)
        if re.findall(r'[A-Za-z].+\s.+\s\d+\s\d.+\s\d+\s\d+\s\d+\s\d.+\s\d.+\s\d.+\s\d.+\s\d.+\s\d\s\d\s(\d.+)',i.text):
            season.append(''.join(re.findall(r'[A-Za-z].+\s.+\s\d+\s\d.+\s\d+\s\d+\s\d+\s\d.+\s\d.+\s\d.+\s\d.+\s\d.+\s\d\s\d\s(\d.+)',i.text)))
        else:
            season.append(np.nan)

In [29]:
df1=pd.DataFrame({'player':player,
                 'matches':matches,
                 'inn':inn,
                 'overs':overs,
                 'maiden':maiden,
                 'runs':runs,
                 'wkts':wkts,
                 'bb_inn':bb_inn,
                 'bb_match':bb_match,
                 'avg':avg,
                 'econ':econ,
                 'sr':sr,
                 '_4w':_4w,
                 '_5w':_5w,
                 'season':season})

In [30]:

df1

,player,matches,inn,overs,maiden,runs,wkts,bb_inn,bb_match,avg,econ,sr,_4w,_5w,season
0,GP Swann (ENG),7,13,298.0,54,906,36,6/90,10/132,25.16,3.04,49.6,3,1,2013
1,SCJ Broad (ENG),7,14,243.5,47,795,34,7/44,11/121,23.38,3.26,43.0,3,1,2013
2,JM Anderson (ENG),7,14,260.2,65,783,31,5/47,10/158,25.25,3.00,50.3,3,1,2013
3,RJ Harris (AUS),4,8,162.1,37,470,24,7/117,9/187,19.58,2.89,40.5,2,0,2013
4,PM Siddle (AUS),5,10,189.5,52,537,17,5/50,8/135,31.58,2.82,67.0,1,0,2013
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
484,Noman Ali (PAK),1,2,35.0,2,118,2,1/54,2/118,59.00,3.37,105.0,0,0,2022
485,J Overton (ENG),1,2,37.0,4,146,2,1/61,2/146,73.00,3.94,111.0,0,0,2022
486,A Phillip (WI),1,2,14.0,2,53,2,2/30,2/53,26.50,3.78,42.0,0,0,2022
487,JE Root (ENG),7,7,32.0,3,133,2,1/23,1/40,66.50,4.15,96.0,0,0,2022
488,Shoriful Islam (BAN),2,2,39.0,9,131,2,2/76,2/76,65.50,3.35,117.0,0,0,2022

In [ ]:
df1.to_csv('bowling(Test).csv', index=False)


#### Batting(Odi)

In [37]:
player=[]
matches=[]
inn=[]
no=[]
runs=[]
hs=[]
avg=[]
bf=[]
sr=[]
_100=[]
_50=[]
_0=[]
_4s=[]
_6s=[]
season=[]
format_=[]


for s in range(2013,2023):    
    url=f'https://stats.espncricinfo.com/ci/engine/stats/index.html?class=2;filter=advanced;orderby=runs;page=1;season={s};template=results;type=batting;view=season'
    response=requests.get(url,headers = {'User-Agent':'Mozilla/5.0'})
    page = BeautifulSoup(response.text)
    for i in page.find_all('tr',class_='data1'):
        if re.findall(r'[A-Za-z].+',i.text):
            player.append(''.join(re.findall(r'[A-Za-z].+',i.text)))
        else:
            player.append(np.nan)
        if re.findall(r'[A-Za-z].+\s(.+)',i.text):
            matches.append(''.join(re.findall(r'[A-Za-z].+\s(.+)',i.text)))
        else:
            matches.append(np.nan)
        if re.findall(r'[A-Za-z].+\s.+\s(\d+)',i.text):
            inn.append(''.join(re.findall(r'[A-Za-z].+\s.+\s(\d+)',i.text)))
        else:
            inn.append(np.nan)
        if re.findall(r'[A-Za-z].+\s.+\s\d+\s(\d+)',i.text):
            no.append(''.join(re.findall(r'[A-Za-z].+\s.+\s\d+\s(\d+)',i.text)))
        else:
            no.append(np.nan)
        if re.findall(r'[A-Za-z].+\s.+\s\d+\s\d+\s(\d.+)',i.text):
            runs.append(''.join(re.findall(r'[A-Za-z].+\s.+\s\d+\s\d+\s(\d.+)',i.text)))
        else:
            runs.append(np.nan)
        if re.findall(r'[A-Za-z].+\s.+\s\d+\s\d+\s\d+\s(\d.+)',i.text):
            hs.append(''.join(re.findall(r'[A-Za-z].+\s.+\s\d+\s\d+\s\d+\s(\d.+)',i.text)))
        else:
            hs.append(np.nan)
        if re.findall(r'[A-Za-z].+\s.+\s\d+\s\d+\s\d+\s\d.+\s(-|\d.+\..+)',i.text):
            avg.append(''.join(re.findall(r'[A-Za-z].+\s.+\s\d+\s\d+\s\d+\s\d.+\s(-|\d.+\..+)',i.text)))
        else:
            avg.append(np.nan)
        if re.findall(r'[A-Za-z].+\s.+\s\d+\s\d+\s\d+\s\d.+\s\d.+\..+\s(\d.+)',i.text):
            bf.append(''.join(re.findall(r'[A-Za-z].+\s.+\s\d+\s\d+\s\d+\s\d.+\s\d.+\..+\s(\d.+)',i.text)))
        else:
            bf.append(np.nan)
        if re.findall(r'[A-Za-z].+\s.+\s\d+\s\d+\s\d+\s\d.+\s\d.+\..+\s\d.+\s(\d.+)',i.text):
            sr.append(''.join(re.findall(r'[A-Za-z].+\s.+\s\d+\s\d+\s\d+\s\d.+\s\d.+\..+\s\d.+\s(\d.+)',i.text)))
        else:
            sr.append(np.nan)
        if re.findall(r'[A-Za-z].+\s.+\s\d+\s\d+\s\d+\s\d.+\s\d.+\..+\s\d.+\s\d.+\s(\d+)',i.text):
            _100.append(''.join(re.findall(r'[A-Za-z].+\s.+\s\d+\s\d+\s\d+\s\d.+\s\d.+\..+\s\d.+\s\d.+\s(\d+)',i.text)))
        else:
            _100.append(np.nan)
        if re.findall(r'[A-Za-z].+\s.+\s\d+\s\d+\s\d+\s\d.+\s\d.+\..+\s\d.+\s\d.+\s\d+\s(\d+)',i.text):
            _50.append(''.join(re.findall(r'[A-Za-z].+\s.+\s\d+\s\d+\s\d+\s\d.+\s\d.+\..+\s\d.+\s\d.+\s\d+\s(\d+)',i.text)))
        else:
            _50.append(np.nan)
        if re.findall(r'[A-Za-z].+\s.+\s\d+\s\d+\s\d+\s\d.+\s\d.+\..+\s\d.+\s\d.+\s\d+\s\d+\s(\d+)',i.text):
            _0.append(''.join(re.findall(r'[A-Za-z].+\s.+\s\d+\s\d+\s\d+\s\d.+\s\d.+\..+\s\d.+\s\d.+\s\d+\s\d+\s(\d+)',i.text)))
        else:
            _0.append(np.nan)
        if re.findall(r'[A-Za-z].+\s.+\s\d+\s\d+\s\d+\s\d.+\s\d.+\..+\s\d.+\s\d.+\s\d+\s\d+\s\d+\s(\d+)',i.text):
            _4s.append(''.join(re.findall(r'[A-Za-z].+\s.+\s\d+\s\d+\s\d+\s\d.+\s\d.+\..+\s\d.+\s\d.+\s\d+\s\d+\s\d+\s(\d+)',i.text)))
        else:
            _4s.append(np.nan)
        if re.findall(r'[A-Za-z].+\s.+\s\d+\s\d+\s\d+\s\d.+\s\d.+\..+\s\d.+\s\d.+\s\d+\s\d+\s\d+\s\d+\s(\d+)',i.text):
            _6s.append(''.join(re.findall(r'[A-Za-z].+\s.+\s\d+\s\d+\s\d+\s\d.+\s\d.+\..+\s\d.+\s\d.+\s\d+\s\d+\s\d+\s\d+\s(\d+)',i.text)))
        else:
            _6s.append(np.nan)
        if re.findall(r'[A-Za-z].+\s.+\s\d+\s\d+\s\d+\s\d.+\s\d.+\..+\s\d.+\s\d.+\s\d+\s\d+\s\d+\s\d+\s\d+\s(\d+)',i.text):
            season.append(''.join(re.findall(r'[A-Za-z].+\s.+\s\d+\s\d+\s\d+\s\d.+\s\d.+\..+\s\d.+\s\d.+\s\d+\s\d+\s\d+\s\d+\s\d+\s(\d+)',i.text)))
        else:
            season.append(np.nan)

In [38]:
df2=pd.DataFrame({'player':player,
                 'matches':matches,
                 'inn':inn,
                 'no':no,
                 'runs':runs,
                 'hs':hs,
                 'avg':avg,
                 'bf':bf,
                 'sr':sr,
                 '_100':_100,
                 '_50':_50,
                 '_0':_0,
                 '_4s':_4s,
                 '_6s':_6s,
                 'season':season})

In [39]:
df2

,player,matches,inn,no,runs,hs,avg,bf,sr,_100,_50,_0,_4s,_6s,season
0,KC Sangakkara (SL),14,13,3,772,169,77.20,842,91.68,2,5,2,78,10,2013
1,S Dhawan (IND),14,14,1,707,116,54.38,756,93.51,3,2,0,77,9,2013
2,Misbah-ul-Haq (PAK),14,14,4,693,96*,69.30,964,71.88,0,9,1,38,13,2013
3,V Kohli (IND),15,13,3,521,115,52.10,564,92.37,2,2,0,54,7,2013
4,Mohammad Hafeez (PAK),14,14,3,517,136*,47.00,595,86.89,2,2,0,47,12,2013
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
487,Tamim Iqbal (BAN),6,6,1,248,62,49.60,302,82.11,0,3,0,37,2,2022
488,KH Prajapati (OMA),8,8,0,244,103,30.50,323,75.54,1,1,1,22,2,2022
489,TWM Latham (NZ),9,9,0,242,69,26.88,296,81.75,0,2,2,20,3,2022
490,CJA Amini (PNG),8,8,0,225,60,28.12,381,59.05,0,2,0,18,0,2022
491,HT Tector (IRE),3,3,0,225,113,75.00,248,90.72,2,0,0,21,8,2022

In [ ]:
df2.to_csv('batting(odi).csv', index=False)

#### Bowling(Odi)

In [40]:
player=[]
matches=[]
inn=[]
overs=[]
maiden=[]
runs=[]
wkts=[]
bb_inn=[]
bb_match=[]
avg=[]
econ=[]
sr=[]
_4w=[]
_5w=[]
season=[]
format_=[]

for s in range(2013,2023):    
    url=f'https://stats.espncricinfo.com/ci/engine/stats/index.html?class=2;filter=advanced;orderby=runs;page=1;season={s};template=results;type=bowling;view=season'
    response=requests.get(url,headers = {'User-Agent':'Mozilla/5.0'})
    page = BeautifulSoup(response.text)
    for i in page.find_all('tr',class_='data1'):
        if re.findall(r'[A-Za-z].+',i.text):
            player.append(''.join(re.findall(r'[A-Za-z].+',i.text)))
        else:
            player.append(np.nan)
        if re.findall(r'[A-Za-z].+\n(\d*)',i.text):
            matches.append(''.join(re.findall(r'[A-Za-z].+\n(\d*)',i.text)))
        else:
            matches.append(np.nan)
        if re.findall(r'[A-Za-z].+\s.+\s(\d+)',i.text):
            inn.append(''.join(re.findall(r'[A-Za-z].+\s.+\s(\d+)',i.text)))
        else:
            inn.append(np.nan)
        if re.findall(r'[A-Za-z].+\s.+\s\d+\s(\d.+)',i.text):
            overs.append(''.join(re.findall(r'[A-Za-z].+\s.+\s\d+\s(\d.+)',i.text)))
        else:
            overs.append(np.nan)
        if re.findall(r'[A-Za-z].+\s.+\s\d+\s\d.+\s(\d+)',i.text):
            maiden.append(''.join(re.findall(r'[A-Za-z].+\s.+\s\d+\s\d.+\s(\d+)',i.text)))
        else:
            maiden.append(np.nan)
        if re.findall(r'[A-Za-z].+\s.+\s\d+\s\d.+\s\d+\s(\d+)',i.text):
            runs.append(''.join(re.findall(r'[A-Za-z].+\s.+\s\d+\s\d.+\s\d+\s(\d+)',i.text)))
        else:
            runs.append(np.nan)
        if re.findall(r'[A-Za-z].+\s.+\s\d+\s\d.+\s\d+\s\d+\s(\d+)',i.text):
            wkts.append(''.join(re.findall(r'[A-Za-z].+\s.+\s\d+\s\d.+\s\d+\s\d+\s(\d+)',i.text)))
        else:
            wkts.append(np.nan)
        if re.findall(r'[A-Za-z].+\s.+\s\d+\s\d.+\s\d+\s\d+\s\d+\s(\d.+)',i.text):
            bb_inn.append(''.join(re.findall(r'[A-Za-z].+\s.+\s\d+\s\d.+\s\d+\s\d+\s\d+\s(\d.+)',i.text)))
        else:
            bb_inn.append(np.nan)
        if re.findall(r'[A-Za-z].+\s.+\s\d+\s\d.+\s\d+\s\d+\s\d+\s\d.+\s(\d.+)',i.text):
            avg.append(''.join(re.findall(r'[A-Za-z].+\s.+\s\d+\s\d.+\s\d+\s\d+\s\d+\s\d.+\s(\d.+)',i.text)))
        else:
            avg.append(np.nan)
        if re.findall(r'[A-Za-z].+\s.+\s\d+\s\d.+\s\d+\s\d+\s\d+\s\d.+\s\d.+\s(\d.+)',i.text):
            econ.append(''.join(re.findall(r'[A-Za-z].+\s.+\s\d+\s\d.+\s\d+\s\d+\s\d+\s\d.+\s\d.+\s(\d.+)',i.text)))
        else:
            econ.append(np.nan)
        if re.findall(r'[A-Za-z].+\s.+\s\d+\s\d.+\s\d+\s\d+\s\d+\s\d.+\s\d.+\s\d.+\s(\d.+)',i.text):
            sr.append(''.join(re.findall(r'[A-Za-z].+\s.+\s\d+\s\d.+\s\d+\s\d+\s\d+\s\d.+\s\d.+\s\d.+\s(\d.+)',i.text)))
        else:
            sr.append(np.nan)
        if re.findall(r'[A-Za-z].+\s.+\s\d+\s\d.+\s\d+\s\d+\s\d+\s\d.+\s\d.+\s\d.+\s\d.+\s(\d)',i.text):
            _4w.append(''.join(re.findall(r'[A-Za-z].+\s.+\s\d+\s\d.+\s\d+\s\d+\s\d+\s\d.+\s\d.+\s\d.+\s\d.+\s(\d)',i.text)))
        else:
            _4w.append(np.nan)
        if re.findall(r'[A-Za-z].+\s.+\s\d+\s\d.+\s\d+\s\d+\s\d+\s\d.+\s\d.+\s\d.+\s\d.+\s\d\s(\d)',i.text):
            _5w.append(''.join(re.findall(r'[A-Za-z].+\s.+\s\d+\s\d.+\s\d+\s\d+\s\d+\s\d.+\s\d.+\s\d.+\s\d.+\s\d\s(\d)',i.text)))
        else:
            _5w.append(np.nan)
        if re.findall(r'[A-Za-z].+\s.+\s\d+\s\d.+\s\d+\s\d+\s\d+\s\d.+\s\d.+\s\d.+\s\d.+\s\d\s\d\s(\d+)',i.text):
            season.append(''.join(re.findall(r'[A-Za-z].+\s.+\s\d+\s\d.+\s\d+\s\d+\s\d+\s\d.+\s\d.+\s\d.+\s\d.+\s\d\s\d\s(\d+)',i.text)))
        else:
            season.append(np.nan)  
        if  p==2:
            format_.append('odi')
        elif p==3:
            format_.append('t20')

In [41]:
df3=pd.DataFrame({'player':player,
                 'matches':matches,
                 'inn':inn,
                 'overs':overs,
                 'maiden':maiden,
                 'runs':runs,
                 'wkts':wkts,
                 'bb_inn':bb_inn,
                 'avg':avg,
                 'econ':econ,
                 'sr':sr,
                 '_4w':_4w,
                 '_5w':_5w,
                 'season':season,
                 'format_':format_})

In [42]:
df3

,player,matches,inn,overs,maiden,runs,wkts,bb_inn,avg,econ,sr,_4w,_5w,season,format_
0,RA Jadeja (IND),15,15,128.5,15,515,25,5/36,20.60,3.99,30.9,1,1,2013,t20
1,HMRKB Herath (SL),12,12,95.5,4,370,21,4/20,17.61,3.86,27.3,1,0,2013,t20
2,Saeed Ajmal (PAK),13,13,112.4,5,510,21,3/25,24.28,4.52,32.1,0,0,2013,t20
3,Junaid Khan (PAK),12,12,93.4,10,467,20,4/15,23.35,4.98,28.1,1,0,2013,t20
4,MJ McClenaghan (NZ),6,6,52.0,1,282,19,4/43,14.84,5.42,16.4,2,0,2013,t20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
487,SI Kamea (PNG),7,7,53.0,3,307,9,3/36,34.11,5.79,35.3,0,0,2022,t20
488,GJ Maxwell (AUS),11,9,66.0,2,324,9,4/52,36.00,4.90,44.0,1,0,2022,t20
489,NK Patel (USA),13,13,94.1,1,492,9,2/26,54.66,5.22,62.7,0,0,2022,t20
490,CA Soper (PNG),8,8,72.0,3,327,9,2/27,36.33,4.54,48.0,0,0,2022,t20
491,TG Southee (NZ),5,5,47.0,4,204,9,4/22,22.66,4.34,31.3,1,0,2022,t20

In [ ]:
df3.to_csv('bowling(odi).csv', index=False)


#### Batting(T20)

In [43]:
player=[]
matches=[]
inn=[]
no=[]
runs=[]
hs=[]
avg=[]
bf=[]
sr=[]
_100=[]
_50=[]
_0=[]
_4s=[]
_6s=[]
season=[]
format_=[]


for s in range(2013,2023):    
    url=f'https://stats.espncricinfo.com/ci/engine/stats/index.html?class=3;filter=advanced;orderby=runs;page=1;season={s};template=results;type=batting;view=season'
    response=requests.get(url,headers = {'User-Agent':'Mozilla/5.0'})
    page = BeautifulSoup(response.text)
    for i in page.find_all('tr',class_='data1'):
        if re.findall(r'[A-Za-z].+',i.text):
            player.append(''.join(re.findall(r'[A-Za-z].+',i.text)))
        else:
            player.append(np.nan)
        if re.findall(r'[A-Za-z].+\s(.+)',i.text):
            matches.append(''.join(re.findall(r'[A-Za-z].+\s(.+)',i.text)))
        else:
            matches.append(np.nan)
        if re.findall(r'[A-Za-z].+\s.+\s(\d+)',i.text):
            inn.append(''.join(re.findall(r'[A-Za-z].+\s.+\s(\d+)',i.text)))
        else:
            inn.append(np.nan)
        if re.findall(r'[A-Za-z].+\s.+\s\d+\s(\d+)',i.text):
            no.append(''.join(re.findall(r'[A-Za-z].+\s.+\s\d+\s(\d+)',i.text)))
        else:
            no.append(np.nan)
        if re.findall(r'[A-Za-z].+\s.+\s\d+\s\d+\s(\d.+)',i.text):
            runs.append(''.join(re.findall(r'[A-Za-z].+\s.+\s\d+\s\d+\s(\d.+)',i.text)))
        else:
            runs.append(np.nan)
        if re.findall(r'[A-Za-z].+\s.+\s\d+\s\d+\s\d+\s(\d.+)',i.text):
            hs.append(''.join(re.findall(r'[A-Za-z].+\s.+\s\d+\s\d+\s\d+\s(\d.+)',i.text)))
        else:
            hs.append(np.nan)
        if re.findall(r'[A-Za-z].+\s.+\s\d+\s\d+\s\d+\s\d.+\s(-|\d.+\..+)',i.text):
            avg.append(''.join(re.findall(r'[A-Za-z].+\s.+\s\d+\s\d+\s\d+\s\d.+\s(-|\d.+\..+)',i.text)))
        else:
            avg.append(np.nan)
        if re.findall(r'[A-Za-z].+\s.+\s\d+\s\d+\s\d+\s\d.+\s\d.+\..+\s(\d.+)',i.text):
            bf.append(''.join(re.findall(r'[A-Za-z].+\s.+\s\d+\s\d+\s\d+\s\d.+\s\d.+\..+\s(\d.+)',i.text)))
        else:
            bf.append(np.nan)
        if re.findall(r'[A-Za-z].+\s.+\s\d+\s\d+\s\d+\s\d.+\s\d.+\..+\s\d.+\s(\d.+)',i.text):
            sr.append(''.join(re.findall(r'[A-Za-z].+\s.+\s\d+\s\d+\s\d+\s\d.+\s\d.+\..+\s\d.+\s(\d.+)',i.text)))
        else:
            sr.append(np.nan)
        if re.findall(r'[A-Za-z].+\s.+\s\d+\s\d+\s\d+\s\d.+\s\d.+\..+\s\d.+\s\d.+\s(\d+)',i.text):
            _100.append(''.join(re.findall(r'[A-Za-z].+\s.+\s\d+\s\d+\s\d+\s\d.+\s\d.+\..+\s\d.+\s\d.+\s(\d+)',i.text)))
        else:
            _100.append(np.nan)
        if re.findall(r'[A-Za-z].+\s.+\s\d+\s\d+\s\d+\s\d.+\s\d.+\..+\s\d.+\s\d.+\s\d+\s(\d+)',i.text):
            _50.append(''.join(re.findall(r'[A-Za-z].+\s.+\s\d+\s\d+\s\d+\s\d.+\s\d.+\..+\s\d.+\s\d.+\s\d+\s(\d+)',i.text)))
        else:
            _50.append(np.nan)
        if re.findall(r'[A-Za-z].+\s.+\s\d+\s\d+\s\d+\s\d.+\s\d.+\..+\s\d.+\s\d.+\s\d+\s\d+\s(\d+)',i.text):
            _0.append(''.join(re.findall(r'[A-Za-z].+\s.+\s\d+\s\d+\s\d+\s\d.+\s\d.+\..+\s\d.+\s\d.+\s\d+\s\d+\s(\d+)',i.text)))
        else:
            _0.append(np.nan)
        if re.findall(r'[A-Za-z].+\s.+\s\d+\s\d+\s\d+\s\d.+\s\d.+\..+\s\d.+\s\d.+\s\d+\s\d+\s\d+\s(\d+)',i.text):
            _4s.append(''.join(re.findall(r'[A-Za-z].+\s.+\s\d+\s\d+\s\d+\s\d.+\s\d.+\..+\s\d.+\s\d.+\s\d+\s\d+\s\d+\s(\d+)',i.text)))
        else:
            _4s.append(np.nan)
        if re.findall(r'[A-Za-z].+\s.+\s\d+\s\d+\s\d+\s\d.+\s\d.+\..+\s\d.+\s\d.+\s\d+\s\d+\s\d+\s\d+\s(\d+)',i.text):
            _6s.append(''.join(re.findall(r'[A-Za-z].+\s.+\s\d+\s\d+\s\d+\s\d.+\s\d.+\..+\s\d.+\s\d.+\s\d+\s\d+\s\d+\s\d+\s(\d+)',i.text)))
        else:
            _6s.append(np.nan)
        if re.findall(r'[A-Za-z].+\s.+\s\d+\s\d+\s\d+\s\d.+\s\d.+\..+\s\d.+\s\d.+\s\d+\s\d+\s\d+\s\d+\s\d+\s(\d+)',i.text):
            season.append(''.join(re.findall(r'[A-Za-z].+\s.+\s\d+\s\d+\s\d+\s\d.+\s\d.+\..+\s\d.+\s\d.+\s\d+\s\d+\s\d+\s\d+\s\d+\s(\d+)',i.text)))
        else:
            season.append(np.nan)

In [44]:
df4=pd.DataFrame({'player':player,
                 'matches':matches,
                 'inn':inn,
                 'no':no,
                 'runs':runs,
                 'hs':hs,
                 'avg':avg,
                 'bf':bf,
                 'sr':sr,
                 '_100':_100,
                 '_50':_50,
                 '_0':_0,
                 '_4s':_4s,
                 '_6s':_6s,
                 'season':season})

In [45]:
df4

,player,matches,inn,no,runs,hs,avg,bf,sr,_100,_50,_0,_4s,_6s,season
0,Ahmed Shehzad (PAK),4,4,1,215,98*,71.66,166,129.51,0,2,0,16,9,2013
1,AJ Finch (AUS),2,2,0,161,156,80.50,68,236.76,1,0,0,12,14,2013
2,AD Hales (ENG),4,4,1,141,94,47.00,99,142.42,0,1,0,17,3,2013
3,JP Duminy (SA),3,3,1,132,51*,66.00,109,121.10,0,2,0,9,3,2013
4,CO Obuya (KENYA),4,4,3,132,75*,132.00,99,133.33,0,1,1,10,4,2013
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,S Wickramasekara (CZK-R),15,15,3,279,63,23.25,202,138.11,0,2,3,19,17,2022
496,VP Thamotharam (MLT),11,11,2,274,57,30.44,162,169.13,0,3,1,15,23,2022
497,DJ Hooda (IND),9,8,2,272,104,45.33,172,158.13,1,0,0,26,12,2022
498,MWR Stokes (GUE),12,11,3,271,48,33.87,239,113.38,0,0,0,21,5,2022
499,LJ Tucker (IRE),12,12,0,268,78,22.33,202,132.67,0,2,1,26,10,2022

In [ ]:
df4.to_csv('batting(t20).csv', index=False)

#### Bowling(T20)

In [46]:

player=[]
matches=[]
inn=[]
overs=[]
maiden=[]
runs=[]
wkts=[]
bb_inn=[]
bb_match=[]
avg=[]
econ=[]
sr=[]
_4w=[]
_5w=[]
season=[]
format_=[]

for s in range(2013,2023):    
    url=f'https://stats.espncricinfo.com/ci/engine/stats/index.html?class=3;filter=advanced;orderby=runs;page=1;season={s};template=results;type=bowling;view=season'
    response=requests.get(url,headers = {'User-Agent':'Mozilla/5.0'})
    page = BeautifulSoup(response.text)
    for i in page.find_all('tr',class_='data1'):
        if re.findall(r'[A-Za-z].+',i.text):
            player.append(''.join(re.findall(r'[A-Za-z].+',i.text)))
        else:
            player.append(np.nan)
        if re.findall(r'[A-Za-z].+\n(\d*)',i.text):
            matches.append(''.join(re.findall(r'[A-Za-z].+\n(\d*)',i.text)))
        else:
            matches.append(np.nan)
        if re.findall(r'[A-Za-z].+\s.+\s(\d+)',i.text):
            inn.append(''.join(re.findall(r'[A-Za-z].+\s.+\s(\d+)',i.text)))
        else:
            inn.append(np.nan)
        if re.findall(r'[A-Za-z].+\s.+\s\d+\s(\d.+)',i.text):
            overs.append(''.join(re.findall(r'[A-Za-z].+\s.+\s\d+\s(\d.+)',i.text)))
        else:
            overs.append(np.nan)
        if re.findall(r'[A-Za-z].+\s.+\s\d+\s\d.+\s(\d+)',i.text):
            maiden.append(''.join(re.findall(r'[A-Za-z].+\s.+\s\d+\s\d.+\s(\d+)',i.text)))
        else:
            maiden.append(np.nan)
        if re.findall(r'[A-Za-z].+\s.+\s\d+\s\d.+\s\d+\s(\d+)',i.text):
            runs.append(''.join(re.findall(r'[A-Za-z].+\s.+\s\d+\s\d.+\s\d+\s(\d+)',i.text)))
        else:
            runs.append(np.nan)
        if re.findall(r'[A-Za-z].+\s.+\s\d+\s\d.+\s\d+\s\d+\s(\d+)',i.text):
            wkts.append(''.join(re.findall(r'[A-Za-z].+\s.+\s\d+\s\d.+\s\d+\s\d+\s(\d+)',i.text)))
        else:
            wkts.append(np.nan)
        if re.findall(r'[A-Za-z].+\s.+\s\d+\s\d.+\s\d+\s\d+\s\d+\s(\d.+)',i.text):
            bb_inn.append(''.join(re.findall(r'[A-Za-z].+\s.+\s\d+\s\d.+\s\d+\s\d+\s\d+\s(\d.+)',i.text)))
        else:
            bb_inn.append(np.nan)
        if re.findall(r'[A-Za-z].+\s.+\s\d+\s\d.+\s\d+\s\d+\s\d+\s\d.+\s(\d.+)',i.text):
            avg.append(''.join(re.findall(r'[A-Za-z].+\s.+\s\d+\s\d.+\s\d+\s\d+\s\d+\s\d.+\s(\d.+)',i.text)))
        else:
            avg.append(np.nan)
        if re.findall(r'[A-Za-z].+\s.+\s\d+\s\d.+\s\d+\s\d+\s\d+\s\d.+\s\d.+\s(\d.+)',i.text):
            econ.append(''.join(re.findall(r'[A-Za-z].+\s.+\s\d+\s\d.+\s\d+\s\d+\s\d+\s\d.+\s\d.+\s(\d.+)',i.text)))
        else:
            econ.append(np.nan)
        if re.findall(r'[A-Za-z].+\s.+\s\d+\s\d.+\s\d+\s\d+\s\d+\s\d.+\s\d.+\s\d.+\s(\d.+)',i.text):
            sr.append(''.join(re.findall(r'[A-Za-z].+\s.+\s\d+\s\d.+\s\d+\s\d+\s\d+\s\d.+\s\d.+\s\d.+\s(\d.+)',i.text)))
        else:
            sr.append(np.nan)
        if re.findall(r'[A-Za-z].+\s.+\s\d+\s\d.+\s\d+\s\d+\s\d+\s\d.+\s\d.+\s\d.+\s\d.+\s(\d)',i.text):
            _4w.append(''.join(re.findall(r'[A-Za-z].+\s.+\s\d+\s\d.+\s\d+\s\d+\s\d+\s\d.+\s\d.+\s\d.+\s\d.+\s(\d)',i.text)))
        else:
            _4w.append(np.nan)
        if re.findall(r'[A-Za-z].+\s.+\s\d+\s\d.+\s\d+\s\d+\s\d+\s\d.+\s\d.+\s\d.+\s\d.+\s\d\s(\d)',i.text):
            _5w.append(''.join(re.findall(r'[A-Za-z].+\s.+\s\d+\s\d.+\s\d+\s\d+\s\d+\s\d.+\s\d.+\s\d.+\s\d.+\s\d\s(\d)',i.text)))
        else:
            _5w.append(np.nan)
        if re.findall(r'[A-Za-z].+\s.+\s\d+\s\d.+\s\d+\s\d+\s\d+\s\d.+\s\d.+\s\d.+\s\d.+\s\d\s\d\s(\d+)',i.text):
            season.append(''.join(re.findall(r'[A-Za-z].+\s.+\s\d+\s\d.+\s\d+\s\d+\s\d+\s\d.+\s\d.+\s\d.+\s\d.+\s\d\s\d\s(\d+)',i.text)))
        else:
            season.append(np.nan)  
        if  p==2:
            format_.append('odi')
        elif p==3:
            format_.append('t20')

In [47]:
df5=pd.DataFrame({'player':player,
                 'matches':matches,
                 'inn':inn,
                 'overs':overs,
                 'maiden':maiden,
                 'runs':runs,
                 'wkts':wkts,
                 'bb_inn':bb_inn,
                 'avg':avg,
                 'econ':econ,
                 'sr':sr,
                 '_4w':_4w,
                 '_5w':_5w,
                 'season':season,
                 'format_':format_})

In [48]:
df5

,player,matches,inn,overs,maiden,runs,wkts,bb_inn,avg,econ,sr,_4w,_5w,season,format_
0,JW Dernbach (ENG),4,3,12.0,0,88,7,3/23,12.57,7.33,10.2,0,0,2013,t20
1,Mohammad Hafeez (PAK),4,4,12.0,1,55,7,3/30,7.85,4.58,10.2,0,0,2013,t20
2,Zulfiqar Babar (PAK),3,3,12.0,1,81,7,3/23,11.57,6.75,10.2,0,0,2013,t20
3,Shakib Al Hasan (BAN),2,2,8.0,0,41,6,4/21,6.83,5.12,8.0,1,0,2013,t20
4,SO Ngoche (KENYA),3,3,11.0,0,87,5,4/34,17.40,7.90,13.2,1,0,2013,t20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,Ngawang Thinley (BHU),7,7,18.3,1,121,13,4/13,9.30,6.54,8.5,1,0,2022,t20
496,L Ngidi (SA),7,7,20.1,0,139,13,5/39,10.69,6.89,9.3,0,1,2022,t20
497,HV Patel (IND),12,11,35.1,0,334,13,4/25,25.69,9.49,16.2,1,0,2022,t20
498,Rashid Khan (AFG),13,13,49.0,0,320,13,3/22,24.61,6.53,22.6,0,0,2022,t20
499,M Sarenac (SRB),9,9,23.0,0,183,13,3/18,14.07,7.95,10.6,0,0,2022,t20

In [ ]:
df5.to_csv('bowling(T20).csv', index=False)

#### allrounder(t20)

In [49]:
player=[]
matches=[]
runs=[]
hs=[]
batting_avg=[]
_100=[]
wkts=[]
bb_inn=[]
bowling_avg=[]
_5w=[]
catches_taken=[]
stumping_made=[]
avg_diff=[]
season=[]

for p in range(1,2):
    for s in range(2013,2023):    
        url=f'https://stats.espncricinfo.com/ci/engine/stats/index.html?class=3;filter=advanced;orderby=matches;season={s};size=200;template=results;type=allround;view=season'
        response=requests.get(url,headers = {'User-Agent':'Mozilla/5.0'})
        page = BeautifulSoup(response.text)
        for i in page.find_all('tr',class_='data1'):
            if re.findall(r'[A-Za-z].+',i.text):
                player.append(''.join(re.findall(r'[A-Za-z].+',i.text)))
            else:
                player.append(np.nan)
            if re.findall(r'[a-zA-Z].+\s(\d+)',i.text):
                matches.append(''.join(re.findall(r'[a-zA-Z].+\s(\d+)',i.text)))
            else:
                matches.append(np.nan)
            if re.findall(r'[a-zA-Z].+\s\d+\s(\d+)',i.text):
                runs.append(''.join(re.findall(r'[a-zA-Z].+\s\d+\s(\d+)',i.text)))
            else:
                runs.append(np.nan)
            if re.findall(r'[a-zA-Z].+\s\d+\s\d+\s(\d*.)',i.text):
                hs.append(''.join(re.findall(r'[a-zA-Z].+\s\d+\s\d+\s(\d*.)',i.text)))
            else:
                hs.append(np.nan)
            if re.findall(r'[a-zA-Z].+\s\d+\s\d+\s\d*.\s(\d.+|-)',i.text):
                batting_avg.append(''.join(re.findall(r'[a-zA-Z].+\s\d+\s\d+\s\d*.\s(\d.+|-)',i.text)))
            else:
                batting_avg.append(np.nan)
            if re.findall(r'[a-zA-Z].+\s\d+\s\d+\s\d*.\s\d.+\s(\d+)',i.text):
                _100.append(''.join(re.findall(r'[a-zA-Z].+\s\d+\s\d+\s\d*.\s\d.+\s(\d+)',i.text)))
            else:
                _100.append(np.nan)
            if re.findall(r'[a-zA-Z].+\s\d+\s\d+\s\d*.\s\d.+\s\d+\s(\d+)',i.text):
                wkts.append(''.join(re.findall(r'[a-zA-Z].+\s\d+\s\d+\s\d*.\s\d.+\s\d+\s(\d+)',i.text)))
            else:
                wkts.append(np.nan)
            if re.findall(r'[a-zA-Z].+\s\d+\s\d+\s\d*.\s\d.+\s\d+\s\d+\s(\d.+)',i.text):
                bb_inn.append(''.join(re.findall(r'[a-zA-Z].+\s\d+\s\d+\s\d*.\s\d.+\s\d+\s\d+\s(\d.+)',i.text)))
            else:
                bb_inn.append(np.nan)
            if re.findall(r'[a-zA-Z].+\s\d+\s\d+\s\d*.\s\d.+\s\d+\s\d+\s\d.+\s(\d.+)',i.text):
                bowling_avg.append(''.join(re.findall(r'[a-zA-Z].+\s\d+\s\d+\s\d*.\s\d.+\s\d+\s\d+\s\d.+\s(\d.+)',i.text)))
            else:
                bowling_avg.append(np.nan)
            if re.findall(r'[a-zA-Z].+\s\d+\s\d+\s\d*.\s\d.+\s\d+\s\d+\s\d.+\s\d.+\s(\d+)',i.text):
                _5w.append(''.join(re.findall(r'[a-zA-Z].+\s\d+\s\d+\s\d*.\s\d.+\s\d+\s\d+\s\d.+\s\d.+\s(\d+)',i.text)))
            else:
                _5w.append(np.nan)
            if re.findall(r'[a-zA-Z].+\s\d+\s\d+\s\d*.\s\d.+\s\d+\s\d+\s\d.+\s\d.+\s\d+\s(\d+)',i.text):
                catches_taken.append(''.join(re.findall(r'[a-zA-Z].+\s\d+\s\d+\s\d*.\s\d.+\s\d+\s\d+\s\d.+\s\d.+\s\d+\s(\d+)',i.text)))
            else:
                catches_taken.append(np.nan)
            if re.findall(r'[a-zA-Z].+\s\d+\s\d+\s\d*.\s\d.+\s\d+\s\d+\s\d.+\s\d.+\s\d+\s\d+\s(\d+)',i.text):
                stumping_made.append(''.join(re.findall(r'[a-zA-Z].+\s\d+\s\d+\s\d*.\s\d.+\s\d+\s\d+\s\d.+\s\d.+\s\d+\s\d+\s(\d+)',i.text)))
            else:
                stumping_made.append(np.nan)
            if re.findall(r'[a-zA-Z].+\s\d+\s\d+\s\d*.\s\d.+\s\d+\s\d+\s\d.+\s\d.+\s\d+\s\d+\s\d+\s(-?\d.+)',i.text):
                avg_diff.append(''.join(re.findall(r'[a-zA-Z].+\s\d+\s\d+\s\d*.\s\d.+\s\d+\s\d+\s\d.+\s\d.+\s\d+\s\d+\s\d+\s(-?\d.+)',i.text)))
            else:
                avg_diff.append(np.nan)
            if re.findall(r'[a-zA-Z].+\s\d+\s\d+\s\d*.\s\d.+\s\d+\s\d+\s\d.+\s\d.+\s\d+\s\d+\s\d+\s-?\d.+\s(\d+)',i.text):
                season.append(''.join(re.findall(r'[a-zA-Z].+\s\d+\s\d+\s\d*.\s\d.+\s\d+\s\d+\s\d.+\s\d.+\s\d+\s\d+\s\d+\s-?\d.+\s(\d+)',i.text)))
            else:
                season.append(np.nan)

In [50]:
df6=pd.DataFrame({'player':player,
                 'matches':matches,
                 'runs':runs,
                 'hs':hs,
                 'batting_avg':batting_avg,
                 '_100':_100,
                 'wkts':wkts,
                 'bb_inn':bb_inn,
                 'bowling_avg':bowling_avg,
                 '_5w':_5w,
                 'catches_taken':catches_taken,
                 'stumping_made':stumping_made,
                 'avg_diff':avg_diff,
                 'season':season})

In [51]:
df6

,player,matches,runs,hs,batting_avg,_100,wkts,bb_inn,bowling_avg,_5w,catches_taken,stumping_made,avg_diff,season
0,Ahmed Shehzad (PAK),4,215,98*,71.66,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,RS Bopara (ENG),4,76,45,76.00,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,JC Buttler (ENG),4,44,27,14.66,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,JW Dernbach (ENG),4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,AD Hales (ENG),4,141,94,47.00,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1613,KR Mayers (WI),9,187,73,23.37,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1614,BJ McCarthy (IRE),9,59,32,14.75,0,5,3/34,53.40,0,6,0,-38.64,2022
1615,BKG Mendis (SL),9,198,60,22.00,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1616,DA Miller (SA),9,158,64*,39.50,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1617,J Miyagi (UGA),9,42,26,10.50,0,14,3/7,13.50,0,2,0,-2.99,2022

In [8]:
df5.to_csv('allrounder(t20).csv')

#### allrounder(test)

In [52]:
player=[]
matches=[]
runs=[]
hs=[]
batting_avg=[]
_100=[]
wkts=[]
bb_inn=[]
bowling_avg=[]
_5w=[]
catches_taken=[]
stumping_made=[]
avg_diff=[]
season=[]

for p in range(1,2):
    for s in range(2013,2023):    
        url=f'https://stats.espncricinfo.com/ci/engine/stats/index.html?class=1;filter=advanced;orderby=matches;season={s};size=200;template=results;type=allround;view=season'
        response=requests.get(url,headers = {'User-Agent':'Mozilla/5.0'})
        page = BeautifulSoup(response.text)
        for i in page.find_all('tr',class_='data1'):
            if re.findall(r'[A-Za-z].+',i.text):
                player.append(''.join(re.findall(r'[A-Za-z].+',i.text)))
            else:
                player.append(np.nan)
            if re.findall(r'[a-zA-Z].+\s(\d+)',i.text):
                matches.append(''.join(re.findall(r'[a-zA-Z].+\s(\d+)',i.text)))
            else:
                matches.append(np.nan)
            if re.findall(r'[a-zA-Z].+\s\d+\s(\d+)',i.text):
                runs.append(''.join(re.findall(r'[a-zA-Z].+\s\d+\s(\d+)',i.text)))
            else:
                runs.append(np.nan)
            if re.findall(r'[a-zA-Z].+\s\d+\s\d+\s(\d*.)',i.text):
                hs.append(''.join(re.findall(r'[a-zA-Z].+\s\d+\s\d+\s(\d*.)',i.text)))
            else:
                hs.append(np.nan)
            if re.findall(r'[a-zA-Z].+\s\d+\s\d+\s\d*.\s(\d.+|-)',i.text):
                batting_avg.append(''.join(re.findall(r'[a-zA-Z].+\s\d+\s\d+\s\d*.\s(\d.+|-)',i.text)))
            else:
                batting_avg.append(np.nan)
            if re.findall(r'[a-zA-Z].+\s\d+\s\d+\s\d*.\s\d.+\s(\d+)',i.text):
                _100.append(''.join(re.findall(r'[a-zA-Z].+\s\d+\s\d+\s\d*.\s\d.+\s(\d+)',i.text)))
            else:
                _100.append(np.nan)
            if re.findall(r'[a-zA-Z].+\s\d+\s\d+\s\d*.\s\d.+\s\d+\s(\d+)',i.text):
                wkts.append(''.join(re.findall(r'[a-zA-Z].+\s\d+\s\d+\s\d*.\s\d.+\s\d+\s(\d+)',i.text)))
            else:
                wkts.append(np.nan)
            if re.findall(r'[a-zA-Z].+\s\d+\s\d+\s\d*.\s\d.+\s\d+\s\d+\s(\d.+)',i.text):
                bb_inn.append(''.join(re.findall(r'[a-zA-Z].+\s\d+\s\d+\s\d*.\s\d.+\s\d+\s\d+\s(\d.+)',i.text)))
            else:
                bb_inn.append(np.nan)
            if re.findall(r'[a-zA-Z].+\s\d+\s\d+\s\d*.\s\d.+\s\d+\s\d+\s\d.+\s(\d.+)',i.text):
                bowling_avg.append(''.join(re.findall(r'[a-zA-Z].+\s\d+\s\d+\s\d*.\s\d.+\s\d+\s\d+\s\d.+\s(\d.+)',i.text)))
            else:
                bowling_avg.append(np.nan)
            if re.findall(r'[a-zA-Z].+\s\d+\s\d+\s\d*.\s\d.+\s\d+\s\d+\s\d.+\s\d.+\s(\d+)',i.text):
                _5w.append(''.join(re.findall(r'[a-zA-Z].+\s\d+\s\d+\s\d*.\s\d.+\s\d+\s\d+\s\d.+\s\d.+\s(\d+)',i.text)))
            else:
                _5w.append(np.nan)
            if re.findall(r'[a-zA-Z].+\s\d+\s\d+\s\d*.\s\d.+\s\d+\s\d+\s\d.+\s\d.+\s\d+\s(\d+)',i.text):
                catches_taken.append(''.join(re.findall(r'[a-zA-Z].+\s\d+\s\d+\s\d*.\s\d.+\s\d+\s\d+\s\d.+\s\d.+\s\d+\s(\d+)',i.text)))
            else:
                catches_taken.append(np.nan)
            if re.findall(r'[a-zA-Z].+\s\d+\s\d+\s\d*.\s\d.+\s\d+\s\d+\s\d.+\s\d.+\s\d+\s\d+\s(\d+)',i.text):
                stumping_made.append(''.join(re.findall(r'[a-zA-Z].+\s\d+\s\d+\s\d*.\s\d.+\s\d+\s\d+\s\d.+\s\d.+\s\d+\s\d+\s(\d+)',i.text)))
            else:
                stumping_made.append(np.nan)
            if re.findall(r'[a-zA-Z].+\s\d+\s\d+\s\d*.\s\d.+\s\d+\s\d+\s\d.+\s\d.+\s\d+\s\d+\s\d+\s(-?\d.+)',i.text):
                avg_diff.append(''.join(re.findall(r'[a-zA-Z].+\s\d+\s\d+\s\d*.\s\d.+\s\d+\s\d+\s\d.+\s\d.+\s\d+\s\d+\s\d+\s(-?\d.+)',i.text)))
            else:
                avg_diff.append(np.nan)
            if re.findall(r'[a-zA-Z].+\s\d+\s\d+\s\d*.\s\d.+\s\d+\s\d+\s\d.+\s\d.+\s\d+\s\d+\s\d+\s-?\d.+\s(\d+)',i.text):
                season.append(''.join(re.findall(r'[a-zA-Z].+\s\d+\s\d+\s\d*.\s\d.+\s\d+\s\d+\s\d.+\s\d.+\s\d+\s\d+\s\d+\s-?\d.+\s(\d+)',i.text)))
            else:
                season.append(np.nan)

In [53]:
df7=pd.DataFrame({'player':player,
                 'matches':matches,
                 'runs':runs,
                 'hs':hs,
                 'batting_avg':batting_avg,
                 '_100':_100,
                 'wkts':wkts,
                 'bb_inn':bb_inn,
                 'bowling_avg':bowling_avg,
                 '_5w':_5w,
                 'catches_taken':catches_taken,
                 'stumping_made':stumping_made,
                 'avg_diff':avg_diff,
                 'season':season})

In [54]:
df7

,player,matches,runs,hs,batting_avg,_100,wkts,bb_inn,bowling_avg,_5w,catches_taken,stumping_made,avg_diff,season
0,JM Anderson (ENG),7,43,16,6.14,0,31,5/47,25.25,3,5,0,-19.11,2013
1,IR Bell (ENG),7,635,113,48.84,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,SCJ Broad (ENG),7,205,65,22.77,0,34,7/44,23.38,3,2,0,-0.60,2013
3,AN Cook (ENG),7,494,130,35.28,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,MJ Prior (ENG),7,176,47,17.60,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1144,JDF Vandersay (SL),1,14,8,7.00,0,2,2/68,34.00,0,1,0,-26.99,2022
1145,GH Vihari (IND),1,31,20,15.50,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1146,N Wagner (NZ),1,4,4,2.00,0,2,2/75,54.00,0,0,0,-51.99,2022
1147,DN Wellalage (SL),1,29,18,14.50,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1148,K Zondo (SA),1,39,23,19.50,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

#### allrounder(odi)

In [55]:
player=[]
matches=[]
runs=[]
hs=[]
batting_avg=[]
_100=[]
wkts=[]
bb_inn=[]
bowling_avg=[]
_5w=[]
catches_taken=[]
stumping_made=[]
avg_diff=[]
season=[]

for p in range(1,2):
    for s in range(2013,2023):    
        url=f'https://stats.espncricinfo.com/ci/engine/stats/index.html?class=2;filter=advanced;orderby=matches;season={s};size=200;template=results;type=allround;view=season'
        response=requests.get(url,headers = {'User-Agent':'Mozilla/5.0'})
        page = BeautifulSoup(response.text)
        for i in page.find_all('tr',class_='data1'):
            if re.findall(r'[A-Za-z].+',i.text):
                player.append(''.join(re.findall(r'[A-Za-z].+',i.text)))
            else:
                player.append(np.nan)
            if re.findall(r'[a-zA-Z].+\s(\d+)',i.text):
                matches.append(''.join(re.findall(r'[a-zA-Z].+\s(\d+)',i.text)))
            else:
                matches.append(np.nan)
            if re.findall(r'[a-zA-Z].+\s\d+\s(\d+)',i.text):
                runs.append(''.join(re.findall(r'[a-zA-Z].+\s\d+\s(\d+)',i.text)))
            else:
                runs.append(np.nan)
            if re.findall(r'[a-zA-Z].+\s\d+\s\d+\s(\d*.)',i.text):
                hs.append(''.join(re.findall(r'[a-zA-Z].+\s\d+\s\d+\s(\d*.)',i.text)))
            else:
                hs.append(np.nan)
            if re.findall(r'[a-zA-Z].+\s\d+\s\d+\s\d*.\s(\d.+|-)',i.text):
                batting_avg.append(''.join(re.findall(r'[a-zA-Z].+\s\d+\s\d+\s\d*.\s(\d.+|-)',i.text)))
            else:
                batting_avg.append(np.nan)
            if re.findall(r'[a-zA-Z].+\s\d+\s\d+\s\d*.\s\d.+\s(\d+)',i.text):
                _100.append(''.join(re.findall(r'[a-zA-Z].+\s\d+\s\d+\s\d*.\s\d.+\s(\d+)',i.text)))
            else:
                _100.append(np.nan)
            if re.findall(r'[a-zA-Z].+\s\d+\s\d+\s\d*.\s\d.+\s\d+\s(\d+)',i.text):
                wkts.append(''.join(re.findall(r'[a-zA-Z].+\s\d+\s\d+\s\d*.\s\d.+\s\d+\s(\d+)',i.text)))
            else:
                wkts.append(np.nan)
            if re.findall(r'[a-zA-Z].+\s\d+\s\d+\s\d*.\s\d.+\s\d+\s\d+\s(\d.+)',i.text):
                bb_inn.append(''.join(re.findall(r'[a-zA-Z].+\s\d+\s\d+\s\d*.\s\d.+\s\d+\s\d+\s(\d.+)',i.text)))
            else:
                bb_inn.append(np.nan)
            if re.findall(r'[a-zA-Z].+\s\d+\s\d+\s\d*.\s\d.+\s\d+\s\d+\s\d.+\s(\d.+)',i.text):
                bowling_avg.append(''.join(re.findall(r'[a-zA-Z].+\s\d+\s\d+\s\d*.\s\d.+\s\d+\s\d+\s\d.+\s(\d.+)',i.text)))
            else:
                bowling_avg.append(np.nan)
            if re.findall(r'[a-zA-Z].+\s\d+\s\d+\s\d*.\s\d.+\s\d+\s\d+\s\d.+\s\d.+\s(\d+)',i.text):
                _5w.append(''.join(re.findall(r'[a-zA-Z].+\s\d+\s\d+\s\d*.\s\d.+\s\d+\s\d+\s\d.+\s\d.+\s(\d+)',i.text)))
            else:
                _5w.append(np.nan)
            if re.findall(r'[a-zA-Z].+\s\d+\s\d+\s\d*.\s\d.+\s\d+\s\d+\s\d.+\s\d.+\s\d+\s(\d+)',i.text):
                catches_taken.append(''.join(re.findall(r'[a-zA-Z].+\s\d+\s\d+\s\d*.\s\d.+\s\d+\s\d+\s\d.+\s\d.+\s\d+\s(\d+)',i.text)))
            else:
                catches_taken.append(np.nan)
            if re.findall(r'[a-zA-Z].+\s\d+\s\d+\s\d*.\s\d.+\s\d+\s\d+\s\d.+\s\d.+\s\d+\s\d+\s(\d+)',i.text):
                stumping_made.append(''.join(re.findall(r'[a-zA-Z].+\s\d+\s\d+\s\d*.\s\d.+\s\d+\s\d+\s\d.+\s\d.+\s\d+\s\d+\s(\d+)',i.text)))
            else:
                stumping_made.append(np.nan)
            if re.findall(r'[a-zA-Z].+\s\d+\s\d+\s\d*.\s\d.+\s\d+\s\d+\s\d.+\s\d.+\s\d+\s\d+\s\d+\s(-?\d.+)',i.text):
                avg_diff.append(''.join(re.findall(r'[a-zA-Z].+\s\d+\s\d+\s\d*.\s\d.+\s\d+\s\d+\s\d.+\s\d.+\s\d+\s\d+\s\d+\s(-?\d.+)',i.text)))
            else:
                avg_diff.append(np.nan)
            if re.findall(r'[a-zA-Z].+\s\d+\s\d+\s\d*.\s\d.+\s\d+\s\d+\s\d.+\s\d.+\s\d+\s\d+\s\d+\s-?\d.+\s(\d+)',i.text):
                season.append(''.join(re.findall(r'[a-zA-Z].+\s\d+\s\d+\s\d*.\s\d.+\s\d+\s\d+\s\d.+\s\d.+\s\d+\s\d+\s\d+\s-?\d.+\s(\d+)',i.text)))
            else:
                season.append(np.nan)

In [56]:
df8=pd.DataFrame({'player':player,
                 'matches':matches,
                 'runs':runs,
                 'hs':hs,
                 'batting_avg':batting_avg,
                 '_100':_100,
                 'wkts':wkts,
                 'bb_inn':bb_inn,
                 'bowling_avg':bowling_avg,
                 '_5w':_5w,
                 'catches_taken':catches_taken,
                 'stumping_made':stumping_made,
                 'avg_diff':avg_diff,
                 'season':season})

In [57]:
df8

,player,matches,runs,hs,batting_avg,_100,wkts,bb_inn,bowling_avg,_5w,catches_taken,stumping_made,avg_diff,season
0,RA Jadeja (IND),15,214,49*,53.50,0,25,5/36,20.60,1,4,0,32.90,2013
1,KD Karthik (IND),15,255,69,31.87,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,V Kohli (IND),15,521,115,52.10,2,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,SK Raina (IND),15,237,65*,29.62,0,2,1/2,57.00,0,12,0,-27.37,2013
4,S Dhawan (IND),14,707,116,54.38,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1824,TJG Pringle (NED),4,6,6,1.50,0,1,1/51,221.00,0,0,0,-219.49,2022
1825,Rohan Mustafa (UAE),4,67,65*,22.33,0,5,2/43,33.20,0,1,0,-10.86,2022
1826,PM Seelaar (NED),4,60,25,15.00,0,2,2/83,100.00,0,1,0,-84.99,2022
1827,A Sharafu (UAE),4,26,22,13.00,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1828,Shoriful Islam (BAN),4,1,1,1.00,0,6,4/34,29.50,0,1,0,-28.49,2022